### ISSUE TITLE
Clarify sub-06 in fLoc

### ISSUE THREAD

**Issue by emdupre** [courtois-neuromod/cneuromod-things#43]
Currently, [the fLoc README](https://github.com/courtois-neuromod/cneuromod-things/blob/main/fLoc/README.md) describes only sub-01, sub-02, and sub-03 participating in the fLoc tasks.

However, sub-06 is also in the accompanying roi folder. To a naive user (me) this is unexpected and surprising. It would be great to clarify this in the README !

**Comment by MarieStLaurent** [comment]
Done!
https://github.com/courtois-neuromod/cneuromod-things/tree/main/fLoc

Since sub-06 could not do the task, I swapped the fLoc GLM contrast with the noise ceilings I estimated w GLMsingle to define subject-specific ROI boundaries around voxels sensititve to stimulus content, but constrained within group-derived parcels from the Kanwisher lab. I identified the noise ceiling masks a bit differently (I replaced `stats-tscores` with `stats-noiseCeil`) under `cneuromod-things/fLoc/rois/sub-06/rois/task-derived`.
